collections:
  sdk:
    output: true
    layout: sdk_pdf

theme: jekyll-theme-slate
title: "Priority SDK"
permalinks: pretty
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "no_intra_emphasis", "fenced_code_blocks", "lax_spacing", "smart"]
repository: mobile/neomib.github.io
layouts_dir:  /resources/_layouts
includes_dir: /resources/_includes
destination: _pdf_site/
defaults:
  -  
    scope:
      path: "sdk"
      type: "pages"
    values:
      layout: "sdk_pdf"

